<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Tim Klustner">
<meta name="dcterms.date" content="2026-09-18">

<title>The war-risk screen: Gleaning signal from noise in maritime conflict shipping – TK</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark-0a6b7249c26820e032cb0bd839ff02b1.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-0e0253f69ad5e6f8bdad49b7f61db11c.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed fullcontent quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">TK</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../papers/index.html"> 
<span class="menu-text">Papers</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../charts/index.html"> 
<span class="menu-text">Data Visualizations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../work/index.html"> 
<span class="menu-text">Work</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../services/index.html"> 
<span class="menu-text">Services</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">About</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">The war-risk screen: Gleaning signal from noise in maritime conflict shipping</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Tim Klustner </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">September 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="the-ras-isa-case" class="level2">
<h2 class="anchored" data-anchor-id="the-ras-isa-case">The Ras Isa case</h2>
<p>By 21:41 local time on 17 April 2025, four US airstrikes arrive at the Ras Isa oil terminal. Into the next morning another ten follow.<span class="citation" data-cites="yemeni_archive2025"><sup><a href="#ref-yemeni_archive2025" role="doc-biblioref">1</a></sup></span> Ras Isa is targeted for bombing, claims the US Central Command, to “eliminate this source of fuel” for the armed group Ansar Allah (the Houthis): sovereign over a third of Yemen’s territory, three-quarters of its people,<span class="citation" data-cites="ukho_yemen_cpin2025"><sup><a href="#ref-ukho_yemen_cpin2025" role="doc-biblioref">2</a></sup></span> and a global petroleum shipping chokepoint, the strait of Bab al-Mandab. The Al Hudaydah Health Office reports 80 people are killed, 150 wounded.<span class="citation" data-cites="yemeni_archive2025"><sup><a href="#ref-yemeni_archive2025" role="doc-biblioref">1</a></sup></span> A figure of 74 killed, 171 wounded circulates on al-Masiryah and Saba via the Houthi Ministry of Health.<span class="citation" data-cites="yemeni_archive2025"><sup><a href="#ref-yemeni_archive2025" role="doc-biblioref">1</a></sup></span> In documenting the bombing’s aftermath, “most of the immediate visual evidence and victim reporting was sourced from Houthi-affiliated media outlets”,<span class="citation" data-cites="yemeni_archive2025"><sup><a href="#ref-yemeni_archive2025" role="doc-biblioref">1</a></sup></span> whose imagery shows burning vehicles, orange-vested rescue personnel, and limbs severed from human bodies.</p>
<p>What, if anything, can synthetic aperture radar (SAR) tell us about the ground effects of this particular attack on Ras Isa? The 17 April attack is only the first sortie against Ras Isa. The terminal is struck again eight days later, 25–26 April, and on 2, 4, and 5 May,<span class="citation" data-cites="yemeni_archive2025"><sup><a href="#ref-yemeni_archive2025" role="doc-biblioref">1</a></sup></span> which makes distinguishing damage from any single event more difficult. The oil terminal also presents two characteristics that confound SAR analysis, in distinct directions:</p>
<ul>
<li><p><strong>Vessel traffic → false positives.</strong> A departed ship’s absence reads as “damage.” The tankers <em>Rival</em> and <em>Akoya Gas</em> were docked pre-strike and left within a day.<span class="citation" data-cites="yemeni_archive2025"><sup><a href="#ref-yemeni_archive2025" role="doc-biblioref">1</a></sup></span></p></li>
<li><p><strong>Low-backscatter terrain → erases true positives.</strong> Water and near-featureless ground both return weak, unstable backscatter, making near-water and bare-sand pixels almost indistinguishable from noise. This confound makes a conventional redness/cyanness damage proxy heuristic unreliable. 64.7% of the case AOI is near-water (within 100 m).</p></li>
</ul>
<p>Six coordinates, corresponding to different features of Ras Isa and its surrounds, are examined for evidence of structural damage generated during the night of 17 April. Both Sentinel-1 (SAR; 12–24 April) and Sentinel-2 (optical; 9–24 April) image pairs occur before the second wave of bombings on 25–26 April, in order to infer directly about the 17 April event. Of the six, only R1, a set of storage tanks 201 m from mapped water, passes the war-risk screen described below.</p>
<div id="fig-context-wide" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-context-wide-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../charts/assets/war_risk_check_ras_isa_context.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-context-wide-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Ras Isa oil terminal and its surrounding peninsula, 9 April 2025 (Sentinel-2 true color, 10 km radius), before the 17 April strike. The terminal, its marine jetties, and vessel traffic in the anchorage are visible.
</figcaption>
</figure>
</div>
</section>
<section id="information-environment" class="level2">
<h2 class="anchored" data-anchor-id="information-environment">Information environment</h2>
<p>War-risk insurance premiums for shipping passing through conflict zones change in response to specific reported incidents, like 17 April. Satellites take between 5 and 12 days to return to a given location<span class="citation" data-cites="esa_sentinel1_facts esa_sentinel2_mission"><sup><a href="#ref-esa_sentinel1_facts" role="doc-biblioref">3</a>,<a href="#ref-esa_sentinel2_mission" role="doc-biblioref">4</a></sup></span> before providing denser independent evidence on the authentic extent of structural damage, so insurance estimates must rely on statements and evidence from self-interested parties intimately linked to the violent event itself.</p>
<p>US Central Command, for example, is unlikely to contradict Secretary of War Pete Hegseth’s characterization, during a 26 March 2025 media appearance in Honolulu, Hawaii,<span class="citation" data-cites="hegseth2025hawaii"><sup><a href="#ref-hegseth2025hawaii" role="doc-biblioref">5</a></sup></span> of the “ongoing campaign against the Houthis” as “devastatingly effective.” And little incentive exists for the “immediate visual evidence and victim reporting” of a party subject to aerial bombardment to disseminate reports about the people and structures <em>not</em> affected by the violence just experienced. The incentive structures between aggressor and aggrieved are not equivalent, yet in this “aftermath gap” their interpretations are by definition subjective and incomplete.</p>
<p>War-risk insurance is concerned with risk to commodities, not people. The salient structures at Ras Isa to evaluate the risk to petroleum as a commodity – whether or not it reaches its destination – are the white circular tanks where transiting petroleum is stored.</p>
<p>A well-resourced analyst can close the aftermath gap using an Automatic Identification System (AIS) ship-tracking feed and Very High Resolution (VHR) optical satellite imagery. They might cross-reference vessel movements with documented bombing records and then inspect the imagery by eye for structural damage. Applying these paid tools to the 17 April Ras Isa case costs at least USD 8,600.</p>
<p>What follows instead is the war-risk screen. It is a replicable three-step check, using entirely open Sentinel-1 and Sentinel-2 imagery, for distinguishing authentic structural damage signal from noise in marine-shipping information environments.</p>
</section>
<section id="what-the-naive-scan-shows" class="level2">
<h2 class="anchored" data-anchor-id="what-the-naive-scan-shows">What the naive scan shows</h2>
<div id="fig-overview" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/ras-isa-overview.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-overview-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: The tested-coordinate zoom (3 km radius), same date. All six coordinates marked: R1 (tank cluster), Dot 1 and Dot 2 (gate junction, outside the walled facility visible at lower right), Quay base (lower quay), Mooring point (vessel-turnover example, screened before testing), and the inland dune (negative control).
</figcaption>
</figure>
</div>
<p>A simple SAR scan of backscatter changes at the terminal before and after 17 April (<a href="#fig-naive-scan" class="quarto-xref">Figure&nbsp;3</a>) returns backscatter increases clustering inland of the northernmost quays (R1) and continuing southeast along the waterline (Quay base, Mooring point). More concentrated backscatter increases are observed at two points along the refining facility’s southern wall (Dot 1, Dot 2). A sixth coordinate (Dune) was selected for investigation because of its unusual shape, evident from pre-bombing optical context (<a href="#fig-overview" class="quarto-xref">Figure&nbsp;2</a>).</p>
<div id="fig-naive-scan" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-naive-scan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../charts/assets/war_risk_check_naive_scan.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-naive-scan-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: The same raw damage-proxy heuristic (R=after, G=B=before), before any correction, over the wider AOI, 11–23 April 2025 (Sentinel-1 VH, DESCENDING). R1, Dot 1, and Dot 2 are the heuristic’s own redness peaks. The dune and quay base are marked for comparison. Mooring point (~790 m east of quay base) is a further redness peak, beside two vessel-shaped streaks. An orange moored vessel visible in the optical record 9 Apr is gone by 24 Apr.&nbsp;Most of these redness peaks are false leads.
</figcaption>
</figure>
</div>
<p>At first blush, this initial analysis seems to generate multiple fruitful leads on which to spend time and resources. These clusters are made more appealing because they present as plausible location targets for the 17 April bombing, just inland of quays and along the refining facility structure. In fact, only one of the five naive backscatter increase clusters proves plausible: the fuel storage tanks at coordinate R1 (<a href="#fig-r1-tank" class="quarto-xref">Figure&nbsp;4</a>).</p>
<div id="fig-r1-tank" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-r1-tank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="../../charts/assets/war_risk_check_r1_tank_composite.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-r1-tank-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: R1, a storage tank at the Ras Isa terminal, before and after the 17 April 2025 strike (Sentinel-1 and Sentinel-2, 11–23 April 2025). Optical true color, then SAR VV, then SAR VH. Before over after. Both SAR bands brighten at the same point in the after row (VV +2.38 dB, VH +3.66 dB). New irregular debris appears where a smooth tank surface previously stood.
</figcaption>
</figure>
</div>
<p>Three outcomes emerge from these six candidates. A moving vehicle generates a false lead, while water or featureless land erases an authentic one; a site exposed to neither preserves a trustworthy signal.</p>
<div id="fig-mooring-quay" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mooring-quay-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/ras-isa-mooring-quay.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mooring-quay-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Mooring point and Quay base (ringed), 11–23 April 2025. Each site’s own optical panel, then its SAR VH panel, before over after. Mooring point. A vessel (orange hull) appears at the mooring in the before panel and is gone in the after panel. This is the naive scan’s false-positive mechanism. Two unrelated vessels further along the quay stay moored in both dates. Quay base. Optical and SAR both stay visually unchanged. Here, near-zero backscatter erases a true lead instead of producing a false one.
</figcaption>
</figure>
</div>
<div id="fig-dune" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-dune-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/ras-isa-dune.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-dune-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: The dune (ringed), same dates and sensor pair. Optical and SAR both stay visually unchanged, displaying the same low-backscatter-terrain mechanism as Quay base.
</figcaption>
</figure>
</div>
<ul>
<li><strong>Vehicles move → generate false leads.</strong> Mooring point (maritime) and Dot 1/Dot 2 (wheeled, at a road junction outside the compound gate) are adjacent to areas with high vehicle traffic. Vehicle presence generally returns strong backscatter. At the Mooring point, the optical record shows the vessel present before and absent after (<a href="#fig-mooring-quay" class="quarto-xref">Figure&nbsp;5</a>). Dot 2 shows a significant negative VV shift (t = −3.07, p = 0.0235). While this change is consistent with an image pair where wheeled traffic was present before and absent after, no optical image pair at 10 m resolution shows the vehicles themselves. Dot 1 is not significant (VV p = 0.1917).</li>
<li><strong>Low-backscatter terrains → erase true leads.</strong> Quay base (maritime waterline) and the inland dune (bare, featureless terrain, low mean damage-proxy brightness 5.9/255) are adjacent to areas of near-zero backscatter (<a href="#fig-mooring-quay" class="quarto-xref">Figure&nbsp;5</a>, <a href="#fig-dune" class="quarto-xref">Figure&nbsp;6</a>). Water and bare sand generally return weak, unstable backscatter. The Quay base’s backscatter shift does not exceed the sensor’s noise floor in the post-bombing inference image; optical imagery ruled out the dune before statistical testing.</li>
<li><strong>Over 100 m inland → preserve trustworthy leads.</strong> R1 (fuel storage tanks) sits 201 m from mapped water (<a href="#tbl-water" class="quarto-xref">Table&nbsp;3</a>), outside both the port’s vehicle-traffic corridors and the AOI’s near-zero-backscatter terrain. Built structures generally return strong, stable backscatter. R1’s shift clears the noise floor, with both VV and VH bands returning statistically significant backscatter increases post-bombing.</li>
</ul>
<div id="tbl-cases" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cases-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Case metadata – Ras Isa oil terminal (Yemen)
</figcaption>
<div aria-describedby="tbl-cases-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 1%">
<col style="width: 13%">
<col style="width: 17%">
<col style="width: 19%">
<col style="width: 48%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>AOI</th>
<th>Violence type</th>
<th>Reference and inference periods / n</th>
<th>SAR reading</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1.1</td>
<td>R1 (fuel tank cluster)</td>
<td>Airstrike/fire (reported)</td>
<td>12 mo pre / 1 mo post; ref_n = 30, inf_n = 3</td>
<td>VV t = +4.33, df = 3.08, p = 0.0214; VH t = +5.46, df = 3.15, p = 0.0107</td>
</tr>
<tr class="even">
<td>1.2</td>
<td>Dot 1 (gate junction)</td>
<td>Airstrike/fire (reported)</td>
<td>12 mo pre / 1 mo post; ref_n = 30, inf_n = 3</td>
<td>VV t = −1.76, df = 2.58, p = 0.1917; VH t = −0.50, df = 2.96, p = 0.6542</td>
</tr>
<tr class="odd">
<td>1.3</td>
<td>Dot 2 (gate junction)</td>
<td>Airstrike/fire (reported)</td>
<td>12 mo pre / 1 mo post; ref_n = 30, inf_n = 3</td>
<td>VV t = −3.07, df = 5.69, p = 0.0235; VH t = −1.19, df = 3.50, p = 0.3069</td>
</tr>
<tr class="even">
<td>1.4</td>
<td>Quay base (lower quay)</td>
<td>Airstrike/fire (reported)</td>
<td>12 mo pre / 1 mo post; ref_n = 30, inf_n = 3</td>
<td>VV t = +1.00, df = 3.15, p = 0.3887; VH t = +1.01, df = 3.38, p = 0.3795</td>
</tr>
<tr class="odd">
<td>1.5</td>
<td>Inland dune (negative control)</td>
<td>Airstrike/fire (reported)</td>
<td>n/a – not statistically tested</td>
<td>Mean brightness 5.9/255 (damage-proxy VH); redness/cyanness heuristic unreliable at near-zero backscatter</td>
</tr>
<tr class="even">
<td>1.6</td>
<td>Mooring point</td>
<td>Vessel turnover (confound, not violence)</td>
<td>n/a – screened pre-test</td>
<td>Redness peak beside two vessel-shaped streaks; optical confirms a moored vessel present 9 Apr, gone by 24 Apr</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="method" class="level2">
<h2 class="anchored" data-anchor-id="method">Method</h2>
<ol type="1">
<li><strong>Verify your anchoring AOI coordinate centers on an inland facility, not a marine transit area.</strong> A port/terminal’s listed coordinate is sometimes its offshore (on-water) anchorage. Centering here fills the AOI with low-backscatter water, which reliably confounds SAR as discussed above. Cross-check your anchor coordinate against OSM Overpass tags (e.g., <code>man_made=storage_tank</code>, <code>landuse=industrial</code>), then run an independent distance check against reported distances from a nearby city before starting testing. Expect sources to differ. In Ras Isa, the naive coordinate is ~52 km from Hodeidah and the independently checked distance is ~56 km. Reuters reported ~55 km on the day of the strike,<span class="citation" data-cites="reuters_ras_isa2025"><sup><a href="#ref-reuters_ras_isa2025" role="doc-biblioref">6</a></sup></span> and later reports give 57–60 km.<span class="citation" data-cites="yemeni_archive2025"><sup><a href="#ref-yemeni_archive2025" role="doc-biblioref">1</a></sup></span></li>
<li><strong>Scan both your optical and SAR frames for connected-component blobs.</strong> Not just the coordinate in question. A full-frame blob scan is what surfaces an authentic candidate. At R1, the optical tank outlines lose circularity between 9 and 24 April. The screen checks optical candidates for SAR backscatter changes with a per-orbit, per-band Welch’s t-test:<span class="citation" data-cites="ballinger2025"><sup><a href="#ref-ballinger2025" role="doc-biblioref">7</a></sup></span> VV +2.38 dB, t = +4.33, p = 0.0214; VH +3.66 dB, t = +5.46, p = 0.0107; Stouffer z = +3.43, p = 0.0006.</li>
<li><strong>Check the optical record for a vessel before trusting a near-shore blob.</strong> A moored-then-departed vessel produces a change blob up to ~60,000 m² along a jetty line. An eye test for ship presence or absence on your optical before/after scenes is sufficient, no statistical test required. Look for a hull present in the before scene and absent in the after scene, as at the Mooring point (<a href="#fig-mooring-quay" class="quarto-xref">Figure&nbsp;5</a>).</li>
</ol>
</section>
<section id="limitations-and-open-questions" class="level2">
<h2 class="anchored" data-anchor-id="limitations-and-open-questions">Limitations and open questions</h2>
<p>The war-risk screen is designed to help infer structural damage candidates using a single before and after image pair (n = 2). Statistical tests use n = 3. As we have seen, transient vehicle traffic amid low-backscatter terrain in either SAR scene can generate false leads while suppressing plausible structural damage signals. Analysts should collect independent post-event data before drawing conclusions from SAR imagery alone. Two additional constraints on the screen as used in the Ras Isa case:</p>
<ul>
<li><strong>Only one SAR flight track covers the AOI.</strong> 4 ASCENDING annual scenes (ref_n = 1 inside 150 m buffer), compared to DESCENDING’s 64 annual scenes.</li>
<li><strong>Cannot confirm or reject candidates by itself.</strong> A single track with no independent third-source corroboration cannot be decisive. That said, R1 is supported as a candidate, presenting a backscatter increase at p &lt; 0.05 for both VV and VH bands. Conversely, discarded candidates (e.g., gate junction) cannot be decisively ruled out as undamaged.</li>
</ul>
</section>
<section id="what-this-means" class="level2">
<h2 class="anchored" data-anchor-id="what-this-means">What this means</h2>
<p>For rapid-assessment outlets and underwriters making near-real-time decisions about maritime risk with limited information, the war-risk screen enables tentative vetting of shipping-related structural damage with minimal open data. For those with access to commercial VHR, it narrows candidate locations across an AOI to the ones worth a costly tasking. The objective is not that its candidates survive further scrutiny, but that this scrutiny is correctly directed.</p>
<p>The estimated cost for the Ras Isa case without the screen: USD 8,609.</p>
<ul>
<li><p><strong>VHR.</strong> Planet SkySat’s published Assured-tasking rate is USD 40/km², 25 km² minimum order.<span class="citation" data-cites="observationdata_tasking2025"><sup><a href="#ref-observationdata_tasking2025" role="doc-biblioref">8</a></sup></span> A 113.1 km² initial pass (USD 4,524) plus four minimum-order zoomed tasks, one per coordinate (4 × 25 km² = 100 km², USD 4,000) ≈ USD 8,524.</p></li>
<li><p><strong>AIS.</strong> Entry-tier commercial subscriptions start around USD 85/month (EUR 80),<span class="citation" data-cites="datadocked_pricing2026"><sup><a href="#ref-datadocked_pricing2026" role="doc-biblioref">9</a></sup></span> often running on coastal receiver networks with thin open-water coverage. Genuine satellite-AIS access for a remote site like Ras Isa is enterprise-quote-only and not publicly priced. The total AIS cost is likely underestimated.</p></li>
</ul>
<p><strong>The war-risk screen cuts the projected cost for the same run by 88%.</strong> The screen replaces the VHR survey pass with free imagery, and replaces AIS with an optical check for vessel turnover in its image pairs. What remains is a single confirmatory VHR tasking per surviving candidate (here, R1).</p>
<p>Given a 25 km² minimum order at USD 40/km², this single VHR task costs around USD 1,000.</p>
</section>
<section id="appendix-data-and-parameters" class="level2">
<h2 class="anchored" data-anchor-id="appendix-data-and-parameters">Appendix: Data and parameters</h2>
<p><strong>Tools, Method steps 1–3.</strong></p>
<ul>
<li><strong>Overpass Turbo.</strong> <a href="https://overpass-turbo.eu">overpass-turbo.eu</a>, <code>man_made=storage_tank</code>/<code>landuse=industrial</code> within ~2 km of the claimed point. Use any map tool’s measure feature for the distance check.</li>
<li><strong>Connected-component labeling.</strong> <code>scipy.ndimage.label</code> on the damage-proxy raster’s redness channel (R − (G+B)/2), full AOI.</li>
<li><strong>Recent low-cloud Sentinel-2 true color.</strong> Before/after, same coordinates, via Copernicus Browser or Google Earth Engine.</li>
</ul>
<div id="tbl-params" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-params-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Per-case tested coordinate, point buffer, and Sentinel-1 track
</figcaption>
<div aria-describedby="tbl-params-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<colgroup>
<col style="width: 1%">
<col style="width: 40%">
<col style="width: 27%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Tested coordinate (lat, lon)</th>
<th>Buffer</th>
<th>Orbit · relative orbit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1.1</td>
<td>15.247410, 42.616510 (OSM <code>man_made=storage_tank</code>)</td>
<td>150 m</td>
<td>descending · 6</td>
</tr>
<tr class="even">
<td>1.2</td>
<td>15.214730, 42.648350 (damage-proxy VH redness peak)</td>
<td>150 m</td>
<td>descending · 6</td>
</tr>
<tr class="odd">
<td>1.3</td>
<td>15.214550, 42.652460 (damage-proxy VH redness peak)</td>
<td>150 m</td>
<td>descending · 6</td>
</tr>
<tr class="even">
<td>1.4</td>
<td>15.234747, 42.631878 (pier shore-anchor, coordinate supplied)</td>
<td>150 m</td>
<td>descending · 6</td>
</tr>
<tr class="odd">
<td>1.5</td>
<td>15.240000, 42.621500 (box centroid, visual scan only)</td>
<td>~2.0 km box, not 150 m</td>
<td>ascending · 116 (visual export only, not point-tested)</td>
</tr>
<tr class="even">
<td>1.6</td>
<td>15.233717, 42.639300 (damage-proxy VH redness peak, computed 2026-09-19)</td>
<td>n/a – visual/optical check only, not point-tested</td>
<td>descending · 6</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-water" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-water-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Distance from each tested coordinate to the nearest JRC Global Surface Water pixel (occurrence ≥ 5%).<span class="citation" data-cites="slagter2024"><sup><a href="#ref-slagter2024" role="doc-biblioref">10</a></sup></span> Only Mooring point and Quay base fall inside this 100 m threshold. Dot 1, Dot 2, and the dune are well clear of mapped water. The dots’ VV backscatter decrease and optically-checked location are consistent with wheeled vehicle presence then absence; the dune’s backscatter instability to its general bare/featureless terrain.
</figcaption>
<div aria-describedby="tbl-water-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Coordinate</th>
<th>Distance to mapped water</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mooring point</td>
<td>42 m</td>
</tr>
<tr class="even">
<td>Quay base</td>
<td>60 m</td>
</tr>
<tr class="odd">
<td>R1</td>
<td>201 m</td>
</tr>
<tr class="even">
<td>Dot 2</td>
<td>218 m</td>
</tr>
<tr class="odd">
<td>Dot 1</td>
<td>350 m</td>
</tr>
<tr class="even">
<td>Dune</td>
<td>552 m</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<div id="refs" class="references csl-bib-body" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-yemeni_archive2025" class="csl-entry" role="listitem">
<div class="csl-left-margin">1. </div><div class="csl-right-inline">Yemeni Archive. <a href="https://yemeniarchive.org/en/investigations/the-u-s-airstrike-on-ras-isa-oil-port/">The <span>U.S.</span> Airstrike on <span>Ras Isa</span> oil port</a>. (2025).</div>
</div>
<div id="ref-ukho_yemen_cpin2025" class="csl-entry" role="listitem">
<div class="csl-left-margin">2. </div><div class="csl-right-inline">UK Home Office. <a href="https://www.gov.uk/government/publications/yemen-country-policy-and-information-notes/country-policy-and-information-note-security-and-humanitarian-situation-yemen-december-2021-accessible-version">Country policy and information note: Security situation, <span>Yemen</span>, <span>March</span> 2025 (accessible version)</a>. (2025).</div>
</div>
<div id="ref-esa_sentinel1_facts" class="csl-entry" role="listitem">
<div class="csl-left-margin">3. </div><div class="csl-right-inline">European Space Agency. <a href="https://www.esa.int/Applications/Observing_the_Earth/Copernicus/Sentinel-1/Facts_and_figures"><span>Sentinel-1</span>: Facts and figures</a>.</div>
</div>
<div id="ref-esa_sentinel2_mission" class="csl-entry" role="listitem">
<div class="csl-left-margin">4. </div><div class="csl-right-inline">European Space Agency. <a href="https://sentiwiki.copernicus.eu/web/s2-mission"><span>Sentinel-2</span>: <span>S2</span> mission</a>.</div>
</div>
<div id="ref-hegseth2025hawaii" class="csl-entry" role="listitem">
<div class="csl-left-margin">5. </div><div class="csl-right-inline">Hegseth, P. <a href="https://www.globalsecurity.org/military/library/news/2025/03/mil-250326-dod02.htm"><span class="nocase">Secretary of Defense Pete Hegseth</span> holds media engagement in <span>Honolulu</span>, <span>Hawaii</span></a>. (2025).</div>
</div>
<div id="ref-reuters_ras_isa2025" class="csl-entry" role="listitem">
<div class="csl-left-margin">6. </div><div class="csl-right-inline">Reuters. <a href="https://www.yahoo.com/news/us-military-strikes-yemens-ras-184811980.html">Deadliest <span>US</span> strike in <span>Yemen</span> kills 74 at oil terminal, <span>Houthis</span> say</a>. (2025).</div>
</div>
<div id="ref-ballinger2025" class="csl-entry" role="listitem">
<div class="csl-left-margin">7. </div><div class="csl-right-inline">Ballinger, O. <a href="https://doi.org/10.1016/j.rse.2025.115025">Open access battle damage detection via <span>Pixel-Wise</span> <span>T-Test</span> on <span>Sentinel-1</span> imagery</a>. <em>Remote Sensing of Environment</em> <strong>331</strong>, 115025 (2025).</div>
</div>
<div id="ref-observationdata_tasking2025" class="csl-entry" role="listitem">
<div class="csl-left-margin">8. </div><div class="csl-right-inline">Observation Data. <a href="https://www.observationdata.com/providers/satellite-tasking-services/">Best satellite tasking services: 9 compared</a>. (2025).</div>
</div>
<div id="ref-datadocked_pricing2026" class="csl-entry" role="listitem">
<div class="csl-left-margin">9. </div><div class="csl-right-inline">Data Docked. <a href="https://datadocked.com/pricing">Maritime <span>API</span> pricing — vessel tracking plans from <span>EUR</span>80/mo</a>.</div>
</div>
<div id="ref-slagter2024" class="csl-entry" role="listitem">
<div class="csl-left-margin">10. </div><div class="csl-right-inline">Slagter, B. <em>et al.</em> <a href="https://doi.org/10.1016/j.rse.2024.114380">Monitoring road development in <span>Congo</span> basin forests with multi-sensor satellite imagery and deep learning</a>. <em>Remote Sensing of Environment</em> <strong>315</strong>, 114380 (2024).</div>
</div>
</div>


</section>

</main> <!-- /main -->
<script>
    document.querySelectorAll('img').forEach(img => {
        img.addEventListener('click', () => {
            const overlay = document.createElement('div');
            overlay.style.cssText = `
            position:fixed; top:0; left:0; width:100%; height:100%;
            background:rgba(0,0,0,0.85); display:flex;
            align-items:center; justify-content:center;
            z-index:9999; cursor:zoom-out;
        `;
            const enlarged = document.createElement('img');
            enlarged.src = img.src;
            enlarged.style.cssText = `max-width:90%; max-height:90vh; object-fit:contain;`;
            overlay.appendChild(enlarged);
            overlay.addEventListener('click', () => overlay.remove());
            document.body.appendChild(overlay);
        });
    });
</script>
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>